### ISSUE TITLE
Can packager create single segment, AES encrypted HLS files that use #EXT-X-BYTERANGE?

### ISSUE THREAD

**Issue by dtiesling** [google/shaka-packager#183]

**Comment by kqyang** [comment]
No, that is not supported right now.

**Comment by g-maulino** [comment]
Hi,
Are #EXT-X-BYTERANGE tags going to be added in a near future?
Thanks

**Comment by kqyang** [comment]
Yes, we are planning to support it in Q2.

**Comment by rkuroiwa** [comment]
I got BYTERANGE working for clear content. Also verified that SAMPLE AES with identity key works on Safari. I couldn't get to verify whether widevine DRM works because there is a bug in shaka player, which is the only player that I know that supports widevine.
I'll close this bug because the feature is implemented as described.
