### ISSUE TITLE
Setting the HLS protocol version (want to move from 6 to 4)

### ISSUE THREAD

**Issue by ebraan** [google/shaka-packager#295]
Hello,

It is not a shaka-packager issue.  It concerns the hls output protocol version. 

Due to browser/Player compatibility , I need to segment output Stream following the HLS protocol version 3 or 4. 

Shaka-packager  currently applies HLS protocol version 6. 

It there a flag (or method) to ask Shaka-packager to format output following HLS protocol v3 or V4?

Many thanks 
Eric

**Comment by rkuroiwa** [comment]
No there is no option to tell the packager to output a specific version of HLS.
"version 6" is hardcoded. This is because if the playlist uses byte ranges with ISO-BMFF, because we don't have I-frame only stream, the version has to be 6 or higher. Also I assumed that almost all players support the latest or latest-1 version.

I think the fix/change would be doing a check like [this ](https://github.com/google/shaka-packager/blob/master/packager/hls/base/media_playlist.cc#L40), [here](https://github.com/google/shaka-packager/blob/master/packager/hls/base/media_playlist.cc#L76).

**Comment by ebraan** [comment]
Hi Rkuroima,

Thanks. Noted. I will find a work around. Maybe use a special packager (ffmpeg+nginx) for people asking me the most compatibility (take into account Win7+ ie11 ) and keep Shaka for people who do not ask for Win7+ ei11. Anyway, Shaka Packager is a great tool :-)

Thank for your quick answer :-)

Regards
Eric
