### ISSUE TITLE
H265 slice header parser does not handle byte alignment

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-packager#383]
Reported to me by a student at [CWIP](http://www.widevine.com/cwip/) who is not a github user:

In media/codecs/h265_parser.cc, in H265Parser::ParseSliceHeader, the parser does not handle `byte_alignment()` from the spec.  `byte_alignment()` reportedly contains at least one bit, and the packager's parser doesn't handle this correctly.

If more information is required, please let me know, and I will follow-up with the person who brought the issue to my attention.  I will be able to do so until end of day Tuesday, April 24 (Pacific time).

**Comment by kqyang** [comment]
Thanks for filing the bug. That is sufficient information. 

This bug may cause the byte_alignment byte to be encrypted, which only happens if byte_alignment() takes the full 8 bits. Since there is no information in that byte_alignment() byte, I doubt any decryptor/parser would actually look into the data of the byte_alignment() byte. I don't think it should cause any decryption/decoding problem.

In any case, we should still fix it for spec compliance.
