### ISSUE TITLE
Question about segment durations (mp4_use_decoding_timestamp_in_timeline?)

### ISSUE THREAD

**Issue by carlanton** [google/shaka-packager#391]
## System info
Ubuntu Bionic

**Shaka Packager Version**: c7e1271-release.

## Issue and steps to reproduce the problem
Download test asset:
```
https://s3.eu-central-1.amazonaws.com/svt-dist-misc/shaka-packager/puppies-988.mp4
https://s3.eu-central-1.amazonaws.com/svt-dist-misc/shaka-packager/puppies-240.mp4
```

**Packager Command**:
```
packager \
  'in=puppies-240.mp4,stream=audio,init_segment=out/a0/a0-init.mp4,segment_template=out/a0/a0-$Number$.mp4,playlist_name=a0/a0.m3u8,hls_group_id=audio,hls_name=ENGLISH' \
  'in=puppies-240.mp4,stream=video,init_segment=out/v0/v0-init.mp4,segment_template=out/v0/v0-$Number$.mp4,playlist_name=v0/v0.m3u8' \
  'in=puppies-988.mp4,stream=video,init_segment=out/v1/v1-init.mp4,segment_template=out/v1/v1-$Number$.mp4,playlist_name=v1/v1.m3u8' \
  --hls_master_playlist_output out/master.m3u8 \
  --generate_static_mpd \
  --mpd_output out/manifest.mpd
```

## What is the expected result?

I expect the first segment of all video representations to be exactly 10 seconds (250000 ticks) since the stream is encoded with a fixed GOP size of 2 seconds.

## What happens instead?

The mpd segment timeline is different for v0 and v1. The first segment of v1 is 1000 ticks (1 frame in 25fps) longer than expected. If I use the flag mp4_use_decoding_timestamp_in_timeline this differens goes away, so I guess it's related to B-frames and pts vs dts? I read the chromium bug issue related to that flag and it seems to be fixed now.

Is the segment timeline in dash supposed to show the decoding timestamp rather than the presentation timestamp?

So, for dash this could be correct, however, I'm more uncertain about HLS. The `#EXTINF` tag for v1.m3u8 says that the first segment has a duration of 10.040 seconds. The spec for HLS says that the value should specify the duration of the media segment.

It this a bug or just over my head? :)

Thanks,
Anton

**Comment by kqyang** [comment]
The problem is related to pts/dts offset. DASH uses presentation timestamp, but Chrome still uses DTS internally in various places due to Chrome's DTS bug.

The first segment has a starting pts at 0.04s; the last sample ends at 10.04s pts. Due to Chrome's DTS bug, we cannot offset the timestamp using presentationTimeOffset in DASH, as it would result in negative DTS. By starting the segment at 0, the segment duration is considered to be 10.04s, although there is a small gap in the beginning of the segment.

Chrome is addressing their DTS bug. It should land in M68 (sometime in July?) . Once Chrome bug is addressed, we can use presentationTimeOffset to offset the pts to 0. 

And yes, for HLS, the duration should really be set to 10s. For the sake of the consistency, it is set to the same value as DASH. We don't think it would cause any problems. Let us know if we are wrong!

Does this address your concern?

**Comment by carlanton** [comment]
Ok, so when M68 is released mp4_use_decoding_timestamp_in_timeline will always be enabled and the segment timelines for my test asset will be the same across representations?

Thank you for the explanation!

**Comment by kqyang** [comment]
`mp4_use_decoding_timestamp_in_timeline` was developed long time. I think it is broken right now. We are going to deprecate `mp4_use_decoding_timestamp_in_timeline` and create another flag (may be something like `normalize_timestamp`) for that and when it is enabled, the segment timelines for your test asset will be the same across representations!

**Comment by carlanton** [comment]
Great! Thank you :)
