### ISSUE TITLE
Query for multi DRM

### ISSUE THREAD

**Issue by sridhard** [google/shaka-packager#420]
We want to use shaka packager to support multiple DRM, Widevine, fairplay and playready. We want to use DASH-CENC(Widevine/playready) and HLS(Fairplay)

1. As per the documentation, there is limited support for playready and fairplay. Playready and fairplay are not usable in production? What are the limitations

2. As per documentation we can package the content for DASH and HLS together and it can generate seperate manifests. Can we package DASH-CENC with playready and widewine , and also HLS with fairplay in the same package? Or we need to create multiple contents when DRM is used?

**Comment by kqyang** [comment]
> 1. As per the documentation, there is limited support for playready and fairplay. Playready and fairplay are not usable in production? What are the limitations

They are both ready for production use. In fact, we have users using them in production. There are some limitations though: 

1. For Playready, Shaka Packager does not support root-leaf license right now.
2. For Fairplay, the user is responsible for managing the keys.

Since you are planning to do multi-DRM, I assume you will be managing the keys yourself anyway. You can use [RawKey](https://google.github.io/shaka-packager/html/tutorials/raw_key.html)  and provide all three types of PSSHs in `--pssh`. You can generate PSSHs using this tool: https://github.com/google/shaka-packager/tree/master/packager/tools/pssh. 

Fairplay is enabled by providing a fairplay pssh: `00000020707373680000000029701FE43CC74A348C5BAE90C7439A4700000000`. You'll also want to set `--hls_key_uri` for Fairplay: https://google.github.io/shaka-packager/html/tutorials/hls.html#hls-options.

> 2. As per documentation we can package the content for DASH and HLS together and it can generate seperate manifests. Can we package DASH-CENC with playready and widewine , and also HLS with fairplay in the same package? Or we need to create multiple contents when DRM is used?

The situation is a bit complicated. It really depends on client support. 

DASH-CENC with playready / widevine typically uses fMP4 with CTR, and the spec allows CBC; while HLS with Fairplay can use either fMP4 or TS as container, but it only supports CBC.

The only overlap is fMP4 with CBC. Unfortunately that is not supported on Chrome yet, although Chrome is working on supporting CBC, probably in M69. I am not sure about the CBC support status in Playready.

So for now, you'll have to create two sets of contents: one for DASH-CENC with Widevine and Playready and one for HLS with Fairplay.

Hope that helps. Let us know if you have more questions.

**Comment by sridhard** [comment]
@kqyang thanks for the detailed explanation.

I have few queries

**Comment by kqyang** [comment]
> 1. As per shaka player documentation, shaka-player doesnot support fairplay DRM now. google/shaka-player#382. Do you have any idea how the users are using fairplay DRM in OSx and IOS? Which client they are using?

Correct. Shaka Player does not support Fairplay right now.

I think the packaged content will work on Safari and QuickTime in OSx and Safari in iOS automatically without a custom player as long as `hls_key_uri` points to a valid Fairplay server. If you are writing your own iOS app, Apple provides documentation on how to handle Fairplay key requests. 

See https://developer.apple.com/streaming/fps/ for details.

An alternative is to use Widevine/Marlin with CENC instead of Fairplay on iOS devices as both Widevine and Marlin have iOS libraries.

> 2. As per shaka-player documentation, We have to provide the license server URL to shaka player. For HLS/fairplay why we need to provide the hls_key_uri? Will this URI is used to fetch the license? or the URI provided to shaka player is used to fetch the license

`hls_key_uri` is the URI that is embedded in HLS playlists, which will be consumed by the HLS client.

Since Shaka Player does not support Fairplay, hls_key_uri is irrelevant to Shaka Player. 

> 3. For playready also we need to provide the license server URL in PSSH. So if we provide the URL during packaging then the content will be binded to the license server and we cannot change the license server. Is my understanding correct?

I am not very familiar with Playready, but I believe the license server URL in PSSH is optional.

> 4. How to mention CBS or CTR during encryption. Is there any parameter for this?

You can specify `--protection_scheme`. See https://google.github.io/shaka-packager/html/documentation.html#general-encryption-options.

`cenc` and `cbcs` are the two common schemes. `cenc` uses AES-CTR without pattern; and `cbcs` uses AES-CBC with pattern. Chrome supports `cenc` only right now and is planning to support `cbcs`; iOS supports `cbcs` only; Android O supports both `cenc` and `cbcs`.

> 5. Do you have any example about how to generate PSSH for playready and fairplay?

PSSH for fairplay is used to signal Fairplay DRM to Shaka Packager and it is fixed: `00000020707373680000000029701FE43CC74A348C5BAE90C7439A4700000000`.

As for Playready, you should be able to get the PSSHs from your Playready license server. We also added experimental support to generate Playready PSSH automatically inside packager recently with option `--generate_playready_pssh`. It can be used with `--enable_widevine_encryption` and `--enable_raw_key_encryption`. If you are using `--enable_playready_encryption`, a Playready pssh will be fetched for you automatically from Playready license server.

Hope that helps.

**Comment by sridhard** [comment]
thanks for the detailed explanation
