### ISSUE TITLE
VP9 codec name in manifest

### ISSUE THREAD

**Issue by lpluto** [google/shaka-packager#469]
## System info
**Operating System**:  Ubuntu 16
**Shaka Packager Version**: v2.2.0

## Issue and steps to reproduce the problem
I'm using MP4 with VP9 as source file to create a MPEG-DASH stream and in the manifest I have a codec name: "vp09.00.00.08.00.02.02.02.00", which seems not to be supported in players. When I change the codec name manually to "vp09.00.10.08" the stream plays in Shaka Player and Dashif players.

What is proper codec name for VP9?

KR,
Lukasz

**Comment by kqyang** [comment]
It does not play because [level](https://www.webmproject.org/vp9/mp4/#codecs-parameter-string) is set to 0, which is not a valid value.

It seems like a problem in your source stream. Can you share the source file and the packager command you used? You can email it to shaka-packager-issues@google.com if it cannot be shared publicly.

We'll look into workaround the problem in Shaka Packager when seeing invalid level values in the source file.

**Comment by kqyang** [comment]
@lpluto Thanks for the content and FFmpeg information. 

> FFMpeg version: ffmpeg version 4.0.2 
libvpx-vp9 version: 1.7.0
FFMpeg command: ffmpeg -i ~/Downloads/tears_of_steel_720p.mov -map 0 -map -0:d -c:v libvpx-vp9 -r 30 -g 60 -keyint_min 60 -profile 0 -level 2.1 -threads 8 -speed 2 -tile-columns 4 -pix_fmt yuv420p -vf scale=640:-2 -b:v 480k -minrate 480k -maxrate 480k -c:a aac -b:a 96k -ac 2 video_vp9.mp4

Unfortunately, FFmpeg does not fill in "level" in vp9 in ISO-BMFF on and before 4.0.2. It is fixed in https://github.com/FFmpeg/FFmpeg/commit/5b6cc3a73acb90df0d4fe5ca8f51527b64592bf8.

I'll prepare a workaround in packager code.

**Comment by kqyang** [comment]
@lpluto Reply to your email to shaka-packager-issues@:

> I used latest snapshot of FFMpeg (N-91876-g8822e2b) and I get codec name "vp09.00.33.08.00.02.02.02.00" now. Unfortunately, when I try to play this MPEG-DASH stream, Shaka Packager informs that is not supported by browser. But, source mp4 plays well in browser.

Thanks for trying out latest FFMpeg. Looks like there are still problems in latest FFmpeg in handling VP9 levels. "33" is not a valid level. I'll submit a fix to FFmpeg repository sometime this week.

The workaround in packager code is done and will be pushed soon.

**Comment by kqyang** [comment]
@lpluto The workaround in packager has been merged! Let us know how it goes.

**Comment by lpluto** [comment]
Thank you @kqyang I created a stream using Shaka Packager with workaround and it plays on Shaka Player.

Could you maybe let me know when you add a fix to FFMpeg?

**Comment by kqyang** [comment]
@lpluto The FFMpeg bug has just been fixed today: https://github.com/FFmpeg/FFmpeg/commit/63c69d51c7532fb6c2460076329b50ec51a0f290 (coincidentally, another developer found the bug and fixed it).

**Comment by kqyang** [comment]
Cherry-picked to v2.2.1.
