### ISSUE TITLE
Understanding gaps (the cause and improved logging)

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#474]
Hello,

we sometimes see warning like 

```
[0912/101610:WARNING:representation.cc(383)] Found a gap of size 168960 > kRoundingErrorGrace (5). The new segment starts at 2758311600 but the previous segment ends at 2758142640.
```

would it be please possible to add information in which stream the gap (or overlap) was detected, like whether it was in stream 0 (which usually is lowest resolution video) or in 5 (audio), etc? Would help us to understand whether the issues are always with just video (and certain bitrates more than others), or just audio, or both.

Also, I am somehow confused about the meaning of this error. I would expect that the gap should be in the multicast input already, right? But we have observed that these issues can happen when the hdd cannot keep up writing the data or when the CPU is overloaded. As an example, after we started processing subtitles using your suggested code change, we were experiencing a huge amount of gaps and seeing highly increased CPU usage. After doing this change https://github.com/jakubvojacek/shaka-packager/commit/daf856fac9681ca4a0fd8dae1c06901080f850f6, the CPU usage dropped down drastically and almost no gaps were happening. 

Would it be possible to add some logging as to what the cause for the gap is? Whether it's in the input, or that CPU cannot handle, or that HDD cannot handle it? Is something like this even possible? We started using packager with `-v 10` which should show all debug info but we're not getting any new info. We tried playing around with `io_cache_size` (but I have never seen warning that it's too small in packager) and with `buffer_size` option for UDP but still cannot get rid of gaps time to time.

Thank you

**Comment by kqyang** [comment]
> would it be please possible to add information in which stream the gap (or overlap) was detected, like whether it was in stream 0 (which usually is lowest resolution video) or in 5 (audio)

Good suggestion! We can include Representation ID and other information (e.g. codecs, resolutions etc) in the logging.

> I would expect that the gap should be in the multicast input already, right? 

There are two typically cause: (1) From the multicast input (2) UDP buffer overrun - either in the sender or in the receiver.

> Would it be possible to add some logging as to what the cause for the gap is? Whether it's in the input, or that CPU cannot handle, or that HDD cannot handle it? Is something like this even possible? 

Yes, we can add some logic to detect if the gap is already presented in the input, which will be probably based on decoding timestamp to avoid complicated computations. It may not be identical to the actual gap detected by the manifest generator later though. 

As for the gaps caused by receiver buffer overrun, you should already be able to see a logging like:
"Circular buffer is full, which can happen if data arrives faster ..." when logging level is set to 1 (you can set the logging level in io_cache to one only and keep the logging level in other files as 0 if you do not want too much logging).

As for the gaps caused by sending buffer overrun, you should be able to see logging in FFmpeg.

It is difficult to know the root cause of the buffer overrun, but it should all bail down to resource contention. I'd suggest monitoring resource usage (CPU, memory etc) and monitoring logging from packager and FFmpeg.

Added to milestone 2.4.

**Comment by jakubvojacek** [comment]
We already got quite neat monitoring in place that reads both ffmpeg and packager logs and we can very nicely see that when there is an error on input reported by ffmpeg, packager gaps a few seconds after. But sometimes the packager gaps without any explanation. We do also keep logs of CPU and memory usage and there are no overloads at that time. 

Looking forward to having this improved logging as that will help us understand and hopefully prevent gaps.

Thank you

**Comment by blueeinstein** [comment]
@jakubvojacek great to hear about the ffmpeg/packager logs deciphering that you are doing, are those in a public project/repo somewhere, that the greater community can benefit from?

**Comment by jakubvojacek** [comment]
Hello, 

its not in a public repo but all that it does is that it parses logs from both ffmpeg and packager periodically and in case there is an error / warning event, it is saved into database. And there is also GUI part available where we can filter it by time and error, but thats just querying the database.
