### ISSUE TITLE
Encrypt segmented media content

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#508]
If I only have just segmented ts files, as far as I know, the files need to be merged back into mp4 before packaging.

But if possible, is there a way to encrypt already segmented files ?

**Comment by kqyang** [comment]
We don't have native support for encrypting segmented files right now, but there are some workarounds.

**Method 1: You can simply concatenate the ts files before packaging, i.e. you don't need to merge them into mp4. Then provide the concatenated ts file to packager as normal.**

**Method 2: Provide each individual ts files to packager and set segment duration to an arbitrary large value. You'll need generate the manifest yourself in this case.**

Here is an example command:

```
$ packager \
  in=segment_x.ts,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Number$.m4s \
  in=segment_x.ts,stream=video,init_segment=video_init.mp4,segment_template=video_$Number$.m4s \
  --enable_raw_key_encryption \
  --keys <keys> \
  --pssh <pssh> \
  --segment_duration 100 \
  --fragment_duration 0
```

Two output files will be generated per stream, xx_init.mp4 and xx_1.m4s. You can ignore all init.mp4 except for the first one; and rename 1.mp4 files accordingly. There is a caveat that the total duration encoded in init.mp4 isn't correct, but since it is not really used in playback, it should be safe to just leave it as is.

Does that answer your question?

**Comment by Jason239** [comment]
I see. 
Thank you very  much !
