### ISSUE TITLE
Marlin Packaging

### ISSUE THREAD

**Issue by sridhard** [google/shaka-packager#525]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
macOS Sierra

**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
Compiled from the github 

## Issue and steps to reproduce the problem
We are using shaka-pakager to package marlin content. The packaging is ok and the content also plays successfully. But the play start time is 6-8 seconds (Not because of CDN response). I have discussed with marlin team and they told 2 issues with shaka packaging. Below are the issues in shaka packaging:

1) Note that the ContentProtection@schemeIdUri is case sensitive.  In the manifest for Marlin it is "urn:uuid:5e629af5-38da-4063-8977-97ffbd9902d4" but it should be "urn:uuid:5E629AF5-38DA-4063-8977-97FFBD9902D4"
2) The default Common Encryption kid for Marlin in the tenc box of the content is different than in the manifest (fcabef00000000000110750100030764 versus FCABEF00000000000110750100030764)

When the ticket #381 is discussed, marlin team told about the case sensitive. When @kqyang implemented marlin I have tested it and reported the case sensitive issue. Marlin packaging should always use small-letters for contentId and schemeIdUri both in manifest and also in the content. @kqyang has solved this issue in manifest but I am not sure about whether it is taken care in content.

Since #381 is closed, I am raising this new ticket to  fix the content packaging guidelines suggested by marlin

**Comment by kqyang** [comment]
@sridhard Thanks for troubleshooting!

> Note that the ContentProtection@schemeIdUri is case sensitive. In the manifest for Marlin it is "urn:uuid:5e629af5-38da-4063-8977-97ffbd9902d4" but it should be "urn:uuid:5E629AF5-38DA-4063-8977-97FFBD9902D4"

Emm.. It looks more like a bug in Marlin side. schemeIdUri for Marlin is a uuid. The uuid specification actually requires the uuid to be in lower case instead of upper case. See [ITU-T X.667 (10/2012)](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-X.667-201210-I!!PDF-E&type=items) section 6.5.4 for details.

>> 6.5.4 Software generating the hexadecimal representation of a UUID shall not use upper case letters. 

That said, I don't mind updating Shaka Packager to comply with Marlin's current requirement. Will address it soon.

> The default Common Encryption kid for Marlin in the tenc box of the content is different than in the manifest (fcabef00000000000110750100030764 versus FCABEF00000000000110750100030764)

I am not sure what it means. The KID field in tenc box is a binary array, which is not in hexadecimal representation, so the "case" does not apply. The manifest has been updated to use lower case per your request in https://github.com/google/shaka-packager/commit/ae3da3772e96904b788d27567932f0828188b196. 

> lasttime you told that the version will be released on dec-1st. Can you please tell me when is the release as per your plan

We are finalizing the release. It should be out next week. Thanks for your patience!

**Comment by sridhard** [comment]
@kqyang thanks for solving the issue.

I am discussing wit marlin team. As of now they have pointed out the above 2 issues. The video is playing now. But the main issue for me is the video start time. It takes 5-8 seconds for video to start. I am checking this issue with marlin team and it looks like it is not shaka-packager issue

**Comment by kqyang** [comment]
@sridhard Thanks for the update. I'll close this issue since it has been addressed. Feel free to reply to this issue or file another issue if there are new updates.
