### ISSUE TITLE
Reduce Shaka Packager official docker image size 

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#535]
Our [docker images](https://hub.docker.com/r/google/shaka-packager/tags) are more than 1 GB each. 

There are a number of ways we can reduce our docker image size:

- Keep only the result binaries. The intermediate artifacts like source code, compilation objects does not need to be present in the final image. This can be achieved using docker's multi-stage builds: https://docs.docker.com/develop/develop-images/multistage-build/.
- Use a smaller base image. We can use [scratch](https://docs.docker.com/develop/develop-images/baseimages/#create-a-simple-parent-image-using-scratch) or [alpine](https://github.com/google/shaka-packager/issues/164).
  - Scratch has a zero-byte base size. It requires the application to be a static binary with zero dependencies. It is more useful if we want to include only one binary in the image. 
  - Alpine is a lightweight Linux distribution with <5MB base size. Since we want to include both packager and mpd_generator in our image, we will go with Alpine. It also allows us to include our pssh tool later.

**Comment by amotl** [comment]
Hi there,

while using Alpine Linux inside a Docker container recently, I became aware of the fact that it is based on [musl libc] instead of [glibc]. As I am not that kind of container guy, this has been new to me but perfectly makes sense regarding their goal of size squeezing after [coming from uclibc already].

However, I believe completely switching to a non-glibc distribution would not be universal enough to make it easy for others to build upon Shaka Packager's official image as baseline image to do other general purpose things with it. Especially when it comes to cross-platform support, the straight Debian distribution is still the most powerful thing around, see also:
> ```
> # Explicitly use Debian for maximum cross-architecture compatibility
> FROM debian:stretch-slim
> ```
> -- https://github.com/docker-library/hello-world/blob/master/Dockerfile.build

This is actually so true and I experienced it on my own workbench when trying to do cross-compilation with Rust against MIPS inside a Docker container the other day: Debian just shines with multiarch support, so I had to switch the Dockerfile [from Ubuntu](https://github.com/rust-embedded/cross/blob/master/docker/mips-unknown-linux-gnu/Dockerfile) to [Debian stretch](https://github.com/hiveeyes/saraswati/blob/master/rust/docker/mips-baseline/Dockerfile) and haven't looked back.

While I have to admit running Shaka Packager on ARM or MIPS will not be its primary target, some people might want to do it nevertheless and then will be able to simply use the canonical/official Docker image for running the build process even against non-amd64 architectures.

You might have got it already: I just personally prefer Debian even more over other distributions after Ubuntu occasionally made me feel bad.

So, other reasons aside, I would definitively try to use plain Debian as a primary candidate to base the Docker image upon and optimize image size by other means if possible. Saying this, I didn't hear about `debian:stretch-slim` before, the baseline seems to be around 12 MB instead of 25 MB for the regular image. This would be totally ok for me for a software like Shaka Packager.

Just my two cents.

Cheers,
Andreas.

[musl libc]: https://en.wikipedia.org/wiki/Musl
[glibc]: https://en.wikipedia.org/wiki/GNU_C_Library
[coming from uclibc already]: https://alpinelinux.org/posts/Alpine-Linux-has-switched-to-musl-libc.html

**Comment by kqyang** [comment]
@amotl Thanks for your comments, but I am not sure if I completely understand your points.

> Especially when it comes to cross-platform support, the straight Debian distribution is still the most powerful thing around

Yes, absolutely. However, to do cross compilation in the docker container for Shaka Packager, we'll need to include the source code in the image, which is what we have now. The image size is more than 1GB, which is unnecessarily big, as for most users, it is sufficient to just have the application binaries.

For this use case, I think it is actually simpler for the user to pull in the code directly from GitHub. We provide docker files for various platforms in https://github.com/google/shaka-packager/tree/master/packager/testing/dockers, which users can reuse to create their own container. If it helps, we can also create Shaka Packager dev images with source code on DockerHub.

For the docker image with just the application binaries, I don't see a difference in functionality with using Debian or Alpine as the base. 

Let me know if I missed anything.
