### ISSUE TITLE
VTT cue gets duplicated if it spans segments

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-packager#573]
## System info
**Operating System**: gLinux
**Shaka Packager Version**: v2.3.0

## Issue and steps to reproduce the problem
When a VTT cue spans a segment boundary, the entire cue is duplicated into two segments.  This results in the cue being displayed twice.

**Packager Command**:

```sh
packager \
  --segment_duration 4 \
  --fragment_duration 4 \
  input=v-0144p-0100k-libx264.mp4,stream=video,playlist_name=playlist_v-0144p-0100k-libx264.mp4.m3u8,segment_template=v-0144p-0100k-libx264-s$Number$.mp4,init_segment=v-0144p-0100k-libx264-init.mp4 \
  input=a-eng-0128k-aac-2c.mp4,stream=audio,playlist_name=playlist_a-eng-0128k-aac-2c.mp4.m3u8,lang=eng,segment_template=a-eng-0128k-aac-2c-s$Number$.mp4,init_segment=a-eng-0128k-aac-2c-init.mp4 \
  input=s-en.webvtt,stream=text,playlist_name=playlist_s-en.webvtt.m3u8,lang=en,segment_template=s-en-s$Number$.vtt \
  --hls_master_playlist_output \
  hls.m3u8
```

The video doesn't seem to matter, but this subtitle is enough to reproduce with any video:
```vtt
WEBVTT FILE

1
00:00:03.837 --> 00:00:07.299
Captain's log, stardate 41636.9.

2
00:00:07.466 --> 00:00:11.845
As feared, our examination of the
overdue Federation freighter Odin,
```

Both of these cues span segment boundaries at 4s and 8s.  Each will appear twice in the output (the first in both s-en-s1.vtt & s-en-s2.vtt, the second in both s-en-s2.vtt & s-en-s3.vtt).

What is the expected result?
The cue should either appear in only one segment or the time range should be split at segment boundaries.

What happens instead?
The cue and its time range are duplicated across the segments, leading to the cue being displayed twice.

See demo: https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8;audiolang=de;textlang=en;uilang=en;play

<Please attach the input files or email to shaka-packager-issues@google.com.>
I can provide complete, exact inputs internally if desired, but any cue that spans segments will reproduce with any video.

**Comment by kqyang** [comment]
@joeyparrish This is by design, implemented according to HLS specification:

https://tools.ietf.org/html/rfc8216#section-3.5

>   Each WebVTT Segment MUST contain all subtitle cues that are intended
   to be displayed during the period indicated by the segment EXTINF
   duration.  The start time offset and end time offset of each cue MUST
   indicate the total display time for that cue, even if part of the cue
   time range is outside the Segment period. 

The specification makes sense to me as I think it is easier to determine if the two cues are the same cue with the same cue start_time and end_time (The player will still need to determine if the two cues are the same cue even if the cue is split at the segment boundary as the users won't want to see the same text disappears and then reappears immediately). The player can also do further optimization to skip the check if the player is playing continuously and the cue has a start time before the current segment's start time.

I thought we had tested the behavior on three common HLS players and made sure it worked as expected: Shaka Player, hls.js, and Safari. It stills works in hls.js and Safari. 

It doesn't work in Shaka Player right now. As what you have observed, the cue appears twice in the output. I think it is a bug in Shaka Player.
