### ISSUE TITLE
Audio and Video segments not the same size after HLS ad cues

### ISSUE THREAD

**Issue by philmoss321** [google/shaka-packager#589]
## System info
**Operating System**: <macOS Mojave, Alpine 3.8>
**Shaka Packager Version**: <v2.3.0, fa7a6d967adf418cc59f41f6b8f308acbab776be>

## Issue and steps to reproduce the problem

**Packager Command**:
`packager 'in=video-output.mp4,stream=audio,segment_template=audio/seg_$Number$.ts,playlist_name=audio/default.m3u8,hls_group_id=audio,hls_name=DEFAULT' 
'in=video-output.mp4,stream=video,segment_template=video/seg_384x216_290866_$Number$.ts,playlist_name=video/stream_384x216_290866.m3u8,iframe_playlist_name=video/iframe_384x216_290866.m3u8' 
--hls_master_playlist_output=master.m3u8 
--segment_duration=6 
--ad_cues=12;33;48`

**Extra steps to reproduce the problem?**
(1) Use a source mp4 with a 2 second keyframe interval
(2) Insert keyframe at 33 seconds.

**What is the expected result?**
I expect that audio segments will match the duration of the video segments. 

**What happens instead?**
Coming out of the ad cue at 33, the video can't segment until the closest i-frame, which is either 5 or 7 seconds later. It chooses to split at 7 seconds. The audio segments at 6 seconds, which leads to audio and video segments that are different durations coming out of an ad cue on an odd timestamp. Also, audio segments aren't exactly 6 seconds like the video segments.

**Example assets**
[example_assets.zip](https://github.com/google/shaka-packager/files/3154114/example_assets.zip)

**Additional information**
I've also attached a metadata file from the source video. I suspect that the audio segments can't be cut at exactly 6 seconds due to the packets not lining up with the i-frames. But we do expect our video and audio segments to match exactly.

**Comment by kqyang** [comment]
@philmoss321 Thanks for the report. Can you share the source mp4 with us? We'll see if we can re-produce the problem you described.

**Comment by kqyang** [comment]
@philmoss321 I checked the generated playlists. The audio/video does align at the cue points.

> Coming out of the ad cue at 33, the video can't segment until the closest i-frame, which is either 5 or 7 seconds later.

Are you talking about the 7th segment? We do not align the segments not at the cue points boundary right now. But if the input stream has fixed GOPs, the video will segment at 6 seconds, which would align audio/video segments.

> Also, audio segments aren't exactly 6 seconds like the video segments.

Yes, and that is expected and it shouldn't be a problem. It is because an AAC packet has exact 1024 samples (which is 0.0213333 for a sample rate of 48000). 

It is possible to align audio and video exactly, for example, for audio sample rate of 48000, you can align video with GOP size 1.6 seconds by setting segment duration to 6.4 seconds.

**Comment by kqyang** [comment]
No updates for about a year. I am closing this issue. @philmoss321 Feel free to reply if it is still a problem for you.
