### ISSUE TITLE
Shaka packager build question

### ISSUE THREAD

**Issue by stevenbajer** [google/shaka-packager#597]
I am located in China mainland and want to try this stream packager as my streaming service function. But the issue as you may know, I can not access the URL:https://chromium.googlesource.com/chromium/tools/depot_tools.git and https://chrome-infra-packages.appspot.com. 

So I can not update gclient and cipd so that each time they can not work correctly.(I see the batch file they need to update many files from the above site when they start to run.

The only way I got the shaka packager is git clone https://github.com/google/shaka-packager.git and download the depot tools form build instructions page.

So below is my step:
1.Use git clone https://github.com/google/shaka-packager.git to download the project source code package to src directory. 
2.Download the depot tools and extract them to depottools directory.
3.Set environment for depot tools.
4.ninja -C out/Release

System display:
ninja -C out/Release
ninja: Entering directory `out/Release'
ninja: fatal: chdir to 'out/Release' - No such file or directory.

Could you give me some suggestions or build instructions about this project without depot tools chains or some other viable way.

Thanks.

**Comment by kqyang** [comment]
@stevenbajer Emm.. I did not know that "chromium.googlesource.com" was blocked in China by Great Firewall. Unfortunately `depot_tools` is required to download the dependencies. Some of the dependencies are hosted at "https://chromium.googlesource.com" too.

When getting the code (https://google.github.io/shaka-packager/html/build_instructions.html#get-the-code), can you use a VPN to bypass the restriction? This is a one time process.

Another option for you is: instead of building Shaka Packager from source, you can use Shaka Packager prebuilt binaries or use dock images: https://google.github.io/shaka-packager/html/documentation.html#getting-shaka-packager.

**Comment by stevenbajer** [comment]
Thank you for your quickly response. 
Unfortunately these days almost all the VPNs can not work normally :(

I will try to find a workable VPN ...

**Comment by stevenbajer** [comment]
@kqyang I brought a virtual server on amazon cloud and set up as a VPN server. Though one day effort and now everything is OK.

:) Thanks

Another question:
Where can I find specific  developer document?

**Comment by kqyang** [comment]
What specific developer document are you looking for? Shaka Packager's documentation is available here: https://google.github.io/shaka-packager/html/.

**Comment by stevenbajer** [comment]
@kqyang got it,thank you very much
