### ISSUE TITLE
WebM (vp8) format playback with PlayReady

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#703]
Is there any player which can playback WebM(vp8) & PlayReady contents packaged by Shaka Packager?
I've tried it in various player on Edge, but it all failed. and Shaka player report this error.
`REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE (6001)`

I think it seems that the webm media file doesn't have encryption information(such as PSSH) and only in mpd.

Did I do anything wrong?

**Comment by kqyang** [comment]
@joeyparrish What does this error mean? Do you know if Edge supports encrypted VP8/WebM playback?

**Comment by joeyparrish** [comment]
I have never tested that configuration, but the error code would indicate that the version of Edge & Windows you have do not support that.  I don't recall ever hearing about VP8 in Edge, but I did hear about VP9.  I'm not sure if it was ever supported in combination with PlayReady.  The results may also differ between the new Chromium-based Edge and the previous version of Edge.

Side-note: You mentioned not finding a PSSH in the WebM file.  When it comes to WebM, it's normal for the PSSH to only appear in the MPD, since PSSH is an MP4 box.  So there would be no way to put a PSSH into a WebM file.  But none of that is related to the playback failure, for what it's worth.

I hope that helps!

**Comment by Jason239** [comment]
Okay, I see.
For now, when I tested, the Chromium-based Edge just only use Widevine, but someday I'll try this test again with PlayReady.

Thanks.
