### ISSUE TITLE
Package DASH and HLS subtitles.

### ISSUE THREAD

**Issue by night91** [google/shaka-packager#722]
Trying to package with 1 instruction video, audio and  captions.

If using the next instruction I am getting
`[0302/212650:ERROR:packager_main.cc(525)] Failed to initialize packager: 3 (INVALID_ARGUMENT): Cannot create text output for MPD with segment output.`

```
packager \
  'input=audio128k.m4a,stream=audio,init_segment=audio/128k/init.m4a,segment_template=audio/128k/$Number$.m4a,language=en,playlist_name=audio128k.m3u8,hls_group_id=audio,hls_name=English' \
  'input=h264_high_1080p_5000.mp4,stream=video,init_segment=video/1800p_5000/init.mp4,segment_template=video/1080p_5000/$Number$.mp4,playlist_name=h264_high_1080p_5000.m3u8' \
  'input=h264_high_720p_2800.mp4,stream=video,init_segment=video/720p_2800/init.mp4,segment_template=video/720p_2800/$Number$.mp4,playlist_name=h264_high_720p_2800.m3u8' \
  'input=h264_high_480p_1400.mp4,stream=video,init_segment=video/480p_1400/init.mp4,segment_template=video/480p_1400/$Number$.mp4,playlist_name=h264_high_480p_1400.m3u8' \
  'input=h264_high_360p_800.mp4,stream=video,init_segment=video/360p_800/init.mp4,segment_template=video/360p_800/$Number$.mp4,playlist_name=h264_high_360p_800.m3u8' \
  'input=subtitle.vtt,stream=text,language=en,segment_template=subtitle/$Number$.vtt,playlist_name=text/main.m3u8,hls_group_id=text,hls_name=English' \
  --hls_master_playlist_output stream.m3u8 \
  --mpd_output stream.mpd
```

Then if removing the segments, I am getting.
`[0302/212744:ERROR:packager_main.cc(525)] Failed to initialize packager: 3 (INVALID_ARGUMENT): segment_template needs to be specified for HLS text output. Single file output is not supported yet.`
```
packager \
  input=audio128k.m4a,stream=audio,output=audio/audio128k.m4a,language=en,playlist_name=audio128k.m3u8,hls_group_id=audio,hls_name=English \
  input=h264_high_1080p_5000.mp4,stream=video,output=video/h264_high_1080p_5000.mp4,playlist_name=h264_high_1080p_5000.m3u8 \
  input=h264_high_720p_2800.mp4,stream=video,output=video/h264_high_720p_2800.mp4,playlist_name=h264_high_720p_2800.m3u8 \
  input=h264_high_480p_1400.mp4,stream=video,output=video/h264_high_480p_1400.mp4,playlist_name=h264_high_480p_1400.m3u8 \
  input=h264_high_360p_800.mp4,stream=video,output=video/h264_high_360p_800.mp4,playlist_name=h264_high_360p_800.m3u8 \
  input=subtitle.vtt,stream=text,output=subtitle/subtitle.vtt,playlist_name=text/main.m3u8,hls_group_id=text,hls_name=English \
  --hls_master_playlist_output stream.m3u8 \
  --mpd_output stream.mpd
```

So, how to get captions added for both DASH and HLS?

**Comment by kqyang** [comment]
> If using the next instruction I am getting
[0302/212650:ERROR:packager_main.cc(525)] Failed to initialize packager: 3 (INVALID_ARGUMENT): Cannot create text output for MPD with segment output.

This is because DASH does not allow segmented WebVTT. 

> Then if removing the segments, I am getting.
[0302/212744:ERROR:packager_main.cc(525)] Failed to initialize packager: 3 (INVALID_ARGUMENT): segment_template needs to be specified for HLS text output. Single file output is not supported yet.

Unfortunately Shaka Packager does not support single WebVTT in HLS yet. See https://github.com/google/shaka-packager/issues/575 for details.

Another way to solve the problem is: https://github.com/google/shaka-packager/issues/651 `dash_only` and `hls_only` support, which @sr1990 is working on right now in https://github.com/google/shaka-packager/pull/721.

I will mark this issue as a duplicate. Feel free to reply if you have more questions.
