### ISSUE TITLE
Big problem with the details of the vp9 codec

### ISSUE THREAD

**Issue by Ballevill** [google/shaka-packager#842]
Hello, I have a big problem with shaka packer, namely in mpd the codec id codecs = "vp09.00.40.08.01.02.02.02.00"

And everything works fine on any pc or android browser but it doesn't work on any tv because tv viewers only support the format:

"video / webm; codecs = \" vp9 \ "": true,
"video / webm; codecs = \" vp09.00.10.08 \ "": false,

So shaka player gives error only after changing mpd file to codecs = "vp9" all televisions start to play vp9 video codec.

Checked on 51 Tv from 2017 to 2019 years, so the problem is big.

My question is how to disable vp9 codec details?

**Comment by kqyang** [comment]
Shaka Packager supports both legacy codec string and the new spec compliant codec string for vp9. It is configurable with flag `--use_legacy_vp9_codec_string`, which is defaulted to false. You can specify `--use_legacy_vp9_codec_string` in the command line to enable it.

See https://github.com/google/shaka-packager/issues/406 for the background.

@joeyparrish Do you think it makes sense for the player to try "vp9" if "vp09.00.10.08" does not work? It can avoid using non spec compliant codec string in latest browsers or having two sets of manifests.

**Comment by Ballevill** [comment]
Thanks, everything works. best regards

**Comment by joeyparrish** [comment]
@kqyang, that sounds reasonable.  I think it could be done as a polyfill on MediaSource.isTypeSupported, since that is both how we filter content and the part of the browser which is out of date.  I think the feature detection would be if isTypeSupported returns true for vp9 and false for a baseline profile of vp09, and under those conditions, we would patch isTypeSupported.

@Ballevill, can you please file a feature request on Shaka Player for that?

**Comment by avelad** [comment]
Issue opened in the ShakaPlayer: https://github.com/google/shaka-player/issues/2870
