### ISSUE TITLE
Question (possible bug): generating VOD MPEG-DASH

### ISSUE THREAD

**Issue by Canta** [google/shaka-packager#910]
## System info
**Operating System**: Ubuntu 20.04
**Shaka Packager Version**: f0a52cbbf2

## Issue and steps to reproduce the problem

When I try to generate a non-live MPEG-DASH, it's always generated as live. This later impacts playback on every MPEG-DASH player.

Steps to reproduce:
  1. Download the following example file: https://drive.google.com/file/d/1Qm6F0z8r3K2DliICep9Dw7cfiaklZ_2T/view
  2. Execute the command stated below.
  3. Check the generated `test.mpd`. You'll see `profiles="urn:mpeg:dash:profile:isoff-live:2011"`.

**Packager Command**:
```
packager \
'in=ccextractor_bugs_allcaps_29fps_leftjustify.m2ts,stream=video,init_segment=output/640p_init.mp4,segment_template=output/640p_$Number$.m4s' \
'in=ccextractor_bugs_allcaps_29fps_leftjustify.m2ts,stream=audio,skip_encryption=1,init_segment=output/audio_init.mp4,segment_template=output/audio_$Number$.m4s,language=ENG' \
'in=ccextractor_bugs_allcaps_29fps_leftjustify.m2ts,stream=text,skip_encryption=1,format=ttml+mp4,init_segment=output/text_init.mp4,segment_template=output/text_$Number$.mp4,language=ENG' \
--mpd_output output/test.mpd
```

**What is the expected result?**
According to [the examples on packager's documentation](https://google.github.io/shaka-packager/html/tutorials/dash.html#examples), this should generate on-demand.

**What happens instead?**
The players see the profile, and accordingly try to play a live MPEG-DASH, which of course doesn't work well.

I don't see any packager option to explicitly state "I want a VOD, not LIVE", for MPEG-DASH. There's one for HLS, but that didn't affect MPEG-DASH in my tests.

So, my question is: is this a bug, is this intended, or I may be doing something wrong?
Thanks in advance.

**Comment by kqyang** [comment]
@Canta Yes, that is intended. 

There are two relevant attributes in DASH MPD related to VOD / Live.

- `@type`, which specifies the type of the Media Presentation. It can be either `static` or `dynamic`, which roughly maps to `VOD` and `Live`.

- `@profiles`, which specifies the Media Presentation Profile. There are a number of profiles. The two most common profiles are `urn:mpeg:dash:profile:isoff-live:2011` and `urn:mpeg:dash:profile:isoff-on-demand:2011`, while the latter does not allow `SegmentList` nor `SegmentTemplate`. 

Since you specified segment template in the command, so Shaka Packager sets the profile to `urn:mpeg:dash:profile:isoff-live:2011`. The mpd type is `static`, so it is still a VOD stream.

Hope that addresses your concern. 

I am closing this bug, but feel free to reply if you have more questions.

**Comment by djeikyb** [comment]
@Canta I just had a similar problem. After seeing the static vs dynamic keywords in kqyang's answer, I found `--generate_static_live_mpd` in the [docs](https://google.github.io/shaka-packager/html/tutorials/dash.html):

> If enabled, generates static mpd. If segment_template is specified in stream descriptors, shaka-packager generates dynamic mpd by default; if this flag is enabled, shaka-packager generates static mpd instead.

I ended up constructing this command to generate both hls and dash formats:

```
packager \
  'in=hd720.mp4,stream=video,playlist_name=hd720/stream.m3u8,init_segment=out/hd720/init.mp4,segment_template=out/hd720/$Number$.m4s' \
  'in=hd1080.mp4,stream=video,playlist_name=hd1080/stream.m3u8,init_segment=out/hd1080/init.mp4,segment_template=out/hd1080/$Number$.m4s' \
  'in=2k.mp4,stream=video,playlist_name=2k/stream.m3u8,init_segment=out/2k/init.mp4,segment_template=out/2k/$Number$.m4s' \
  'in=4k.mp4,stream=video,playlist_name=4k/stream.m3u8,init_segment=out/4k/init.mp4,segment_template=out/4k/$Number$.m4s' \
  --hls_playlist_type VOD \
  --hls_master_playlist_output=out/main.m3u8 \
  --generate_static_live_mpd \
  --mpd_output=out/main.mpd
```

The `--hls_playlist_type VOD` is unnecessary right now, but I kinda like being explicit about it.
